---
title: "clean_hys"
output: html_document
date: "2024-02-15"
---

```{r}
library(tidyverse)
library(readxl)

folder <- "./ncw_data/raw_data/HYS/"
state_file <- "./ncw_data/raw_data/HYS/State-level HYS.xlsx"

# get filenames
files <- tibble(filename = list.files(folder))
```
County Data
```{r}
# make a list of filepaths for just the county data
county_filepath_list <-
  files %>%
  mutate(
    filepaths = paste0(folder,filename),
    filename = NULL
  ) %>%
  filter(
    grepl("County", filepaths)
  )

# create an empty list to store data frames
county_data_list <- list()

# read and store data
for (filepath in county_filepath_list$filepaths) { 
  data <- 
     read_xlsx( 
      filepath, sheet = "Grade 10" # open the relevant sheet
    ) 
  county_data_list <- append(county_data_list, list(data))
}

# clean and filter data
county_data <- 
  bind_rows(county_data_list) %>%
  filter(
    County %in% c(4, 9, 13, 19, 24) & # filter for counties
    Variable %in% c("D20", "D14", "D90_16",	"D21_16", "D15", "D63", "H54", "H25") # filter for relevant vars
  ) %>%
  select(
    County,
    Year,
    Variable,
    ResponseCategoryText,
    ResponsePercent,
    ResponseCI
  ) %>%
  rename(
    Location = County, 
    Value = ResponsePercent
  ) %>%
  mutate(
    Location = case_when(
      Location == 4 ~ "Chelan",
      Location == 9 ~ "Douglas",
      Location == 13 ~ "Grant",
      Location == 19 ~ "Kittitas",
      Location == 24 ~ "Okanogan",
      TRUE ~ as.character(Location)
    ),
    LowerCI = Value - ResponseCI,
    UpperCI = Value + ResponseCI
  )

head(county_data)
```
Substance
```{r}
# alcohol *** NEED TO FIX CI****
state_alc <-
  read_xlsx( 
    state_file, sheet = "Alcohol" # read in relevant sheet
  ) %>%
  rename(
    Value = Percent
  ) %>%
  mutate(
    Indicator = "youth_alcohol",
    UpperCI = Value + CI,
    LowerCI = Value - CI
  ) %>%
  select(
    Location,
    Year,
    Value,
    UpperCI,
    LowerCI,
    Indicator
  )

county_alc <- 
  county_data %>%
  filter(
    Variable == "D20" &
    ResponseCategoryText != "None"
  ) %>%
  mutate(
    Indicator = "youth_alcohol"
  ) %>%
  group_by(Location, Year, Indicator) %>%
  summarise(Value = sum(Value)) %>% 
  ungroup() %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

alc_data <- bind_rows(state_alc, county_alc)

write_csv(alc_data, "./ncw_data/cleaned_data/youthalc_data.csv")

# cigarettes
state_cig <-
  read_xlsx( 
    state_file, sheet = "Cigarettes" # read in relevant sheet
  ) %>%
  mutate(
    Indicator = "youth_cigarettes"
  ) %>%
  rename(
    Value = Percent
  ) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

county_cig <- 
  county_data %>%
  filter(
    Variable == "D14" &
    ResponseCategoryText != "None"
  ) %>%
  mutate(
    Indicator = "youth_cigarettes"
  ) %>%
  group_by(Location, Year, Indicator) %>%
  summarise(Value = sum(Value)) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

cig_data <- bind_rows(state_cig, county_cig)

write_csv(cig_data, "./ncw_data/cleaned_data/youthcig_data.csv")

# E-cigarettes 
state_ecig <-
  read_xlsx( 
    state_file, sheet = "E-cigarettes" # read in relevant sheet
  ) %>%
  mutate(
    Indicator = "youth_e-cigarettes"
  ) %>%
  rename(
    Value = Percent
  ) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

county_ecig <- 
  county_data %>%
  filter(
    Variable == "D90_16" &
    ResponseCategoryText != "0 days"
  ) %>%
  mutate(
    Indicator = "youth_e-cigarettes"
  ) %>%
  group_by(Location, Year, Indicator) %>%
  summarise(Value = sum(Value)) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

ecig_data <- bind_rows(state_ecig, county_ecig)

write_csv(ecig_data, "./ncw_data/cleaned_data/youthecig_data.csv")

# Marijuana
state_marijuana <-
  read_xlsx( 
    state_file, sheet = "Marijuana" # read in relevant sheet
  ) %>%
  mutate(
    Indicator = "youth_marijuana"
  ) %>%
  rename(
    Value = Percent
  ) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

county_marijuana <- 
  county_data %>%
  filter(
    Variable == "D21_16" &
    ResponseCategoryText != "0 days"
  ) %>%
  mutate(
    Indicator = "youth_marijuana"
  ) %>%
  group_by(Location, Year, Indicator) %>%
  summarise(Value = sum(Value)) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

marijuana_data <- bind_rows(state_marijuana, county_marijuana)

write_csv(marijuana_data, "./ncw_data/cleaned_data/youthmarijuana_data.csv")

# other tobacco
state_tobacco <-
  read_xlsx( 
    state_file, sheet = "Other tobacco" # read in relevant sheet
  ) %>%
  mutate(
    Indicator = "youth_other_tobacco"
  ) %>%
  rename(
    Value = Percent
  ) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

county_tobacco <- 
  county_data %>%
  filter(
    Variable == "D15" &
    ResponseCategoryText != "None"
  ) %>%
  mutate(
    Indicator = "youth_other_tobacco"
  ) %>%
  group_by(Location, Year, Indicator) %>%
  summarise(Value = sum(Value)) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

tobacco_data <- bind_rows(state_tobacco, county_tobacco)

write_csv(tobacco_data, "./ncw_data/cleaned_data/youthtobacco_data.csv")

# other illegal drugs
state_othdrugs <-
  read_xlsx( 
    state_file, sheet = "Other illegal drugs" # read in relevant sheet
  ) %>%
  mutate(
    Indicator = "youth_other_illegal_drugs"
  ) %>%
  rename(
    Value = Percent
  ) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

county_othdrugs <- 
  county_data %>%
  filter(
    Variable == "D63" &
    ResponseCategoryText != "None"
  ) %>%
  mutate(
    Indicator = "youth_other_illegal_drugs"
  ) %>%
  group_by(Location, Year, Indicator) %>%
  summarise(Value = sum(Value)) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

othdrugs_data <- bind_rows(state_othdrugs, county_othdrugs)

write_csv(othdrugs_data, "./ncw_data/cleaned_data/youthothdrugs_data.csv")
```
Suicidal Ideation
```{r}
# clean state data for youth SI
state_si <-
  read_xlsx( 
    state_file, sheet = "Suicide" # read in relevant sheet
  ) %>%
  mutate(
    Indicator = "youth_si",
    LowerCI = Percent - CI,
    UpperCI = Percent + CI
  ) %>%
  rename(
    Value = Percent
  ) %>%
  select(
    Location,
    Year,
    Value,
    LowerCI,
    UpperCI,
    Indicator
  )

# clean county data for youth SI
county_si <-
  county_data %>%
  filter(
    Variable == "H54" &
    ResponseCategoryText == "Yes"
  ) %>%
  mutate(
    Indicator = "youth_si"
  ) %>%
  select(
    Location,
    Year,
    Value,
    LowerCI,
    UpperCI,
    Indicator
  )

si_data <- bind_rows(state_si, county_si)

write_csv(si_data, "./ncw_data/cleaned_data/youthsi_data.csv")
```
Dental Care
```{r}
# clean state data for youth dental
state_yd <-
  read_xlsx( 
    state_file, sheet = "Dental care" # read in relevant sheet
  ) %>%
  mutate(
    Indicator = "youth_dental",
    LowerCI = Percent - CI,
    UpperCI = Percent + CI
  ) %>%
  rename(
    Value = Percent
  ) %>%
  select(
    Location,
    Year,
    Value,
    LowerCI,
    UpperCI,
    Indicator
  )

# clean county data for youth dental
county_yd <-
  county_data %>%
  filter(
    Variable == "H25" &
    ResponseCategoryText == "During the past 12 months"
  ) %>%
  mutate(
    Indicator = "youth_dental"
  ) %>%
  select(
    Location,
    Year,
    Value,
    LowerCI,
    UpperCI,
    Indicator
  )

yd_data <- bind_rows(state_yd, county_yd)

write_csv(yd_data, "./ncw_data/cleaned_data/youthdent_data.csv")
```

