---
title: "clean_hys"
output: html_document
date: "2024-02-15"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Package Management
Ensure all required packages are installed 
```{r}
required_packages <- c("here", "tidyverse", "readxl")

install_if_missing <- function(package) {
  if (!requireNamespace(package, quietly = TRUE)) {
    install.packages(package)
  }
}

lapply(required_packages, install_if_missing)
```
# Load Libraries
Load the required libraries. 
```{r}
library(tidyverse)
library(here)
library(readxl)
```
# File Paths
Define paths to relevant files.
```{r}
folder <- here("ncw_data", "raw_data", "HYS")

state_file <- here("ncw_data", "raw_data", "HYS", "State-level HYS.xlsx")

cleaned_sub_data_file <- here("ncw_data", "cleaned_data", "youthallsubuse_data.csv")
cleaned_si_data_file <- here("ncw_data", "cleaned_data", "youthsi_data.csv")
cleaned_dent_data_file <- here("ncw_data", "cleaned_data", "youthdent_data.csv")

# get filenames
files <- tibble(filename = list.files(folder))

# make a list of filepaths for just the county data
county_filepath_list <-
  files %>%
  mutate(
    filepaths = paste0(folder, "/", filename),
    filename = NULL
  ) %>%
  filter(
    grepl("County", filepaths)
  )
```
# Cleaning
Read and clean the data.
## Prepare County Data
```{r}
county_data_list <- list()

# read and store data
for (filepath in county_filepath_list$filepaths) { 
  data <- 
    read_xlsx( 
      filepath, sheet = "Grade 10" # open the relevant sheet
    ) %>%
    filter(
      County %in% c(4, 9, 13, 19, 24) & # filter for counties
      Variable %in% c("D20", "D14", "D90_16",	"D21_16", "D15", "D63", "H54", "H25") # filter for relevant vars
    ) %>%
    select(
      County,
      Year,
      Variable,
      ResponseCategoryText,
      ResponsePercent,
      ResponseCI
    ) %>%
    rename(
      Location = County, 
      Value = ResponsePercent
    ) %>%
    mutate(
      Location = case_when(
        Location == 4 ~ "Chelan",
        Location == 9 ~ "Douglas",
        Location == 13 ~ "Grant",
        Location == 19 ~ "Kittitas",
        Location == 24 ~ "Okanogan",
        TRUE ~ as.character(Location)
      ),
      LowerCI = Value - ResponseCI,
      UpperCI = Value + ResponseCI
    )
  county_data_list <- append(county_data_list, list(data))
}

county_data <- bind_rows(county_data_list)
```
## Clean Youth Substance Data
```{r}
# Alcohol
state_alc <-
  read_xlsx( 
    state_file, sheet = "Alcohol" # read in relevant sheet
  ) %>%
  rename(
    Value = Percent
  ) %>%
  mutate(
    Indicator = "youth_alcohol"
  ) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

county_alc <- 
  county_data %>%
  filter(
    Variable == "D20" &
    ResponseCategoryText != "None"
  ) %>%
  mutate(
    Indicator = "youth_alcohol"
  ) %>%
  group_by(Location, Year, Indicator) %>%
  summarise(Value = sum(Value)) %>% 
  ungroup() %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

alc_data <- bind_rows(state_alc, county_alc)

# Cigarettes
state_cig <-
  read_xlsx( 
    state_file, sheet = "Cigarettes" # read in relevant sheet
  )  %>%
  rename(
    Value = Percent
  ) %>%
  mutate(
    Indicator = "youth_cigarettes"
  ) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

county_cig <- 
  county_data %>%
  filter(
    Variable == "D14" &
    ResponseCategoryText != "None"
  ) %>%
  mutate(
    Indicator = "youth_cigarettes"
  ) %>%
  group_by(Location, Year, Indicator) %>%
  summarise(Value = sum(Value)) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

cig_data <- bind_rows(state_cig, county_cig)

# E-cigarettes 
state_ecig <-
  read_xlsx( 
    state_file, sheet = "E-cigarettes" # read in relevant sheet
  ) %>%
  rename(
    Value = Percent
  ) %>%
  mutate(
    Indicator = "youth_e-cigarettes"
  ) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

county_ecig <- 
  county_data %>%
  filter(
    Variable == "D90_16" &
    ResponseCategoryText != "0 days"
  ) %>%
  mutate(
    Indicator = "youth_e-cigarettes"
  ) %>%
  group_by(Location, Year, Indicator) %>%
  summarise(Value = sum(Value)) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

ecig_data <- bind_rows(state_ecig, county_ecig)

# Marijuana
state_marijuana <-
  read_xlsx( 
    state_file, sheet = "Marijuana" # read in relevant sheet
  ) %>%
  rename(
    Value = Percent
  ) %>%
  mutate(
    Indicator = "youth_marijuana"
  ) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

county_marijuana <- 
  county_data %>%
  filter(
    Variable == "D21_16" &
    ResponseCategoryText != "0 days"
  ) %>%
  mutate(
    Indicator = "youth_marijuana"
  ) %>%
  group_by(Location, Year, Indicator) %>%
  summarise(Value = sum(Value)) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

marijuana_data <- bind_rows(state_marijuana, county_marijuana)

# Other Tobacco
state_tobacco <-
  read_xlsx( 
    state_file, sheet = "Other tobacco" # read in relevant sheet
  ) %>%
  rename(
    Value = Percent
  ) %>%
  mutate(
    Indicator = "youth_other_tobacco"
  ) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

county_tobacco <- 
  county_data %>%
  filter(
    Variable == "D15" &
    ResponseCategoryText != "None"
  ) %>%
  mutate(
    Indicator = "youth_other_tobacco"
  ) %>%
  group_by(Location, Year, Indicator) %>%
  summarise(Value = sum(Value)) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

tobacco_data <- bind_rows(state_tobacco, county_tobacco)

# Other Illegal Drugs
state_othdrugs <-
  read_xlsx( 
    state_file, sheet = "Other illegal drugs" # read in relevant sheet
  ) %>%
  rename(
    Value = Percent
  ) %>%
  mutate(
    Indicator = "youth_other_illegal_drugs"
  ) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

county_othdrugs <- 
  county_data %>%
  filter(
    Variable == "D63" &
    ResponseCategoryText != "None"
  ) %>%
  mutate(
    Indicator = "youth_other_illegal_drugs"
  ) %>%
  group_by(Location, Year, Indicator) %>%
  summarise(Value = sum(Value)) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )

othdrugs_data <- bind_rows(state_othdrugs, county_othdrugs)

youthallsubuse_data <- bind_rows(alc_data, cig_data, ecig_data, marijuana_data, tobacco_data, othdrugs_data)
```
## Clean Youth Suicidal Ideation Data
```{r}
# clean state data for youth SI
state_si <-
  read_xlsx( 
    state_file, sheet = "Suicide" # read in relevant sheet
  ) %>%
  mutate(
    Indicator = "youth_si",
    LowerCI = Percent - CI,
    UpperCI = Percent + CI
  ) %>%
  rename(
    Value = Percent
  ) %>%
  select(
    Location,
    Year,
    Value,
    LowerCI,
    UpperCI,
    Indicator
  )

# clean county data for youth SI
county_si <-
  county_data %>%
  filter(
    Variable == "H54" &
    ResponseCategoryText == "Yes"
  ) %>%
  mutate(
    Indicator = "youth_si"
  ) %>%
  select(
    Location,
    Year,
    Value,
    LowerCI,
    UpperCI,
    Indicator
  )

si_data <- bind_rows(state_si, county_si)
```

## Clean Youth Dental Data
```{r}
# clean state data for youth dental
state_yd <-
  read_xlsx( 
    state_file, sheet = "Dental care" # read in relevant sheet
  ) %>%
  mutate(
    Indicator = "youth_dental",
    LowerCI = Percent - CI,
    UpperCI = Percent + CI
  ) %>%
  rename(
    Value = Percent
  ) %>%
  select(
    Location,
    Year,
    Value,
    LowerCI,
    UpperCI,
    Indicator
  )

# clean county data for youth dental
county_yd <-
  county_data %>%
  filter(
    Variable == "H25" &
    ResponseCategoryText == "During the past 12 months"
  ) %>%
  mutate(
    Indicator = "youth_dental"
  ) %>%
  select(
    Location,
    Year,
    Value,
    LowerCI,
    UpperCI,
    Indicator
  )

yd_data <- bind_rows(state_yd, county_yd)
```

# Write Clean Data
Write the cleaned data csv file.
```{r}
write_csv(youthallsubuse_data, cleaned_sub_data_file)
write_csv(si_data, cleaned_si_data_file)
write_csv(yd_data, cleaned_dent_data_file)
```
