---
title: "clean_stroke"
output: html_document
date: "2023-10-27"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Package Management
Ensure all required packages are installed 
```{r}
required_packages <- c("here", "tidyverse")

install_if_missing <- function(package) {
  if (!requireNamespace(package, quietly = TRUE)) {
    install.packages(package)
  }
}

lapply(required_packages, install_if_missing)
```
# Load Libraries
Load the required libraries. 
```{r}
library(tidyverse)
library(here)
```
# File Paths
Define paths to relevant files.
```{r}
folder <- here("ncw_data", "raw_data", "PLACES")

cleaned_data_file <- here("ncw_data", "cleaned_data", "stroke_data.csv")

# get filenames
files <- tibble(filename = list.files(folder))

# make a list of filepaths
filepath_list <-
  files %>%
  mutate(
    filepaths = paste0(folder, "/", filename)
  ) %>%
  mutate(
    filename = NULL
  ) 

```
# Cleaning
Read and clean the data.
```{r}
data_list <- list()

# read and store data from all files, clean and filter
for (filepath in filepath_list$filepaths) { 
  data <- 
    read_csv(
      filepath, show_col_types = FALSE
    ) %>%
    filter(
      StateAbbr == 'WA' &
      Measure == 'Stroke among adults aged >=18 years' &
      LocationName %in% c('Chelan','Douglas','Grant','Kittitas','Okanogan') &
      Data_Value_Type == 'Age-adjusted prevalence'
    ) %>%
    rename(
      Location = LocationName,
      Value = Data_Value,
      LowerCI = Low_Confidence_Limit,
      UpperCI = High_Confidence_Limit
    ) %>%
    mutate(
      Indicator = "stroke"
    ) %>%
    select(
      Location,
      Year,
      Value,
      LowerCI,
      UpperCI,
      Indicator
    )
  data_list <- append(data_list, list(data))
}

combined_data <- bind_rows(data_list)
```
# Write Clean Data
Write the cleaned data csv file.
```{r}
write_csv(combined_data, cleaned_data_file)
```