---
title: "clean_kindvax"
output: html_document
date: "2023-10-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Package Management
Ensure all required packages are installed 
```{r}
required_packages <- c("here", "tidyverse", "readxl")

install_if_missing <- function(package) {
  if (!requireNamespace(package, quietly = TRUE)) {
    install.packages(package)
  }
}

lapply(required_packages, install_if_missing)
```
# Load Libraries
Load the required libraries. 
```{r}
library(tidyverse)
library(here)
library(readxl)
```
# File Paths
Define paths to relevant files.
```{r}
folder <- here("ncw_data", "raw_data", "WA IIS", "Kindergarten Vaccination")

cleaned_data_file <- here("ncw_data", "cleaned_data", "kindvax_data.csv")

# get filenames
files <- tibble(filename = list.files(folder))

# make a list of filepaths for just the county data
county_filepath_list <-
  files %>%
  mutate(
    filepaths = paste0(folder, "/", filename)
  ) %>%
  mutate(
    filename = NULL
  ) %>%
  filter(
    grepl("County", filepaths)
  )

# make a list of filepaths for just the state data
state_filepath_list <-
  files %>%
  mutate(
    filepaths = paste0(folder, "/", filename)
  ) %>%
  mutate(
    filename = NULL
  ) %>%
  filter(
    grepl("State", filepaths)
  )
```
# Cleaning
Read and clean the data.
## Clean County Data
```{r}
# create an empty list to store county data
county_data_list <- list()

# read, store, filter, clean county data 
for (filepath in county_filepath_list$filepaths) { 
  data <- 
     read_xlsx( 
      filepath, skip = 3
    ) %>%
    select(
      1:7,
      -"Count...5",
      -"Enrollment...6",
      -Disease,
      -Grade
    ) %>%
    rename(
      Value = "%...7",
      Location = County,
      Year = "School Year"
    ) %>%
    mutate(
      Value = (as.numeric(gsub("%","",Value)))*100,
      Indicator = "kindvax"
    )
  county_data_list <- append(county_data_list, list(data))
}

county_data <- bind_rows(county_data_list)
```
## Clean State Data
```{r}
# create an empty list to store state data
state_data_list <- list()

# read, store, filter, clean state data 
for (filepath in state_filepath_list$filepaths) { 
  data <- 
     read_csv( 
      filepath, show_col_types = FALSE 
    ) %>%
    mutate(
      Location = "WA"
    ) %>%
    rename(
      Year = "Year Alias",
      Value = Percent
    ) %>%
    mutate(
      Value = Value*100,
      Indicator = "kindvax"
    ) %>%
    select(
      Location,
      Year,
      Value,
      Indicator
    )
  state_data_list <- append(state_data_list, list(data))
}

state_data <- bind_rows(state_data_list)
```
## Combine Cleaned Data
```{r}
combined_data <- rbind(state_data, county_data)
```
# Write Clean Data
Write the cleaned data csv file.
```{r}
write_csv(combined_data, cleaned_data_file)
```
