---
title: "clean_dentists"
output: html_document
date: "2023-10-27"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Package Management
Ensure all required packages are installed 
```{r}
required_packages <- c("here", "tidyverse", "readxl")

install_if_missing <- function(package) {
  if (!requireNamespace(package, quietly = TRUE)) {
    install.packages(package)
  }
}

lapply(required_packages, install_if_missing)
```
# Load Libraries
Load the required libraries. 
```{r}
library(tidyverse)
library(here)
library(readxl)
```
# File Paths
Define paths to relevant files.
```{r}
folder <- here("ncw_data", "raw_data", "HRSA", "Dentists")

cleaned_data_file <- here("ncw_data", "cleaned_data", "dentists_data.csv")

# get filenames
files <- tibble(filename = list.files(folder))

# make a list of filepaths
filepath_list <-
  files %>%
  mutate(
    filepaths = paste0(folder, "/", filename)
  ) %>%
  mutate(
    filename = NULL
  ) 
```
# Cleaning
Read and clean the data.
```{r}
data_list <- list()

# read and store data from all files and grab Year
for (filepath in filepath_list$filepaths) { 
  data <- 
    read_xlsx(
      filepath, skip = 3
    ) %>%
    mutate( # grab last 4 of the string
      Year = substring(Source, nchar(Source) - 4 + 1, nchar(Source)) 
    )
  data_list <- append(data_list, list(data))
}

# clean and filter data
combined_data <- 
  bind_rows(data_list) %>%
  mutate(
    Location = ifelse(is.na(County), `State/Territory`, County)
  ) %>%
  filter(
    Location %in% c("Chelan County, WA","Douglas County, WA","Grant County, WA","Kittitas County, WA", "Okanogan County, WA", "Washington")
  ) %>%
  mutate( 
    Year = paste0(Year,"-",as.integer(Year)+1), # turn into YYYY-YYYY format
    Indicator = "dentists",
    Location = gsub(" County, WA","", Location),
    Location = gsub("Washington", "WA", Location)
  ) %>%
  rename(
    Value = `Rate (per 100,000 population)`
  ) %>%
  select(
    Location,
    Year,
    Value,
    Indicator
  )
```
# Write Clean Data
Write the cleaned data csv file.
```{r}
write_csv(combined_data, cleaned_data_file)
```

