---
title: "clean_hosp"
output: html_document
date: "2024-05-08"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Package Management
Ensure all required packages are installed 
```{r}
required_packages <- c("here", "tidyverse")

install_if_missing <- function(package) {
  if (!requireNamespace(package, quietly = TRUE)) {
    install.packages(package)
  }
}

lapply(required_packages, install_if_missing)
```
# Load Libraries
Load the required libraries. 
```{r}
library(tidyverse)
library(here)
```
# File Paths
Define paths to relevant files.
```{r}
folder <- here("ncw_data", "raw_data", "CHAT", "Hospitalizations")

cleaned_data_file <- here("ncw_data", "cleaned_data", "hosp_data.csv")

# get filenames
files <- tibble(filename = list.files(folder))

# make a list of filepaths
filepath_list <-
  files %>%
  mutate(
    filepaths = paste0(folder, "/", filename)
  ) %>%
  mutate(
    filename = NULL
  ) 
```
# Cleaning
Read and clean the data.
```{r}
data_list <- list()

# read and store and clean data from all files 
for (filepath in filepath_list$filepaths) { 
  data <- 
    read.csv(filepath, skip=3) %>%
    filter(
      !is.na(Geography) & Geography != "" # filter out extra rows
    ) %>%
    rename(
      Location = Geography,
      Value = Age.Adjusted.Rate, # per 100,000
      LowerCI = Age.Adjusted.Lower.CI,
      UpperCI = Age.Adjusted.Upper.CI,
      Diagnosis_Group = Diagnosis.Group
    ) %>%
    mutate(
      Indicator = "hospitalizations",
      Location = gsub("State Total", "WA", Location)
    ) %>%
    group_by(Location, Year) %>%
    top_n(5, Value) %>% # grab top 5 reasons for hospitalization for each location and year
    ungroup() %>%
    select(
      Location,
      Year,
      Value,
      LowerCI,
      UpperCI,
      Diagnosis_Group,
      Indicator
    )
  data_list <- append(data_list, list(data))
}

combined_data <- bind_rows(data_list)
```
# Write Clean Data
Write the cleaned data csv file.
```{r}
write_csv(combined_data, cleaned_data_file)
```

