---
title: "clean_abuseneg"
output: html_document
date: "2024-02-15"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Package Management
Ensure all required packages are installed 
```{r package-management, message=FALSE, warning=FALSE}
required_packages <- c("here", "tidyverse")

install_if_missing <- function(package) {
  if (!requireNamespace(package, quietly = TRUE)) {
    install.packages(package)
  }
}

lapply(required_packages, install_if_missing)
```
# Load Libraries
Load the required libraries. 
```{r}
library(tidyverse)
library(here)
```
# File Paths
Define paths to relevant files.
```{r}
raw_data_file <- here("ncw_data", "raw_data", "DCYF", "Abuse and Neglect", "DCYF_AbuseNeglect_All_2006_2019.csv")

cleaned_data_file <- here("ncw_data", "cleaned_data", "abuseneg_data.csv")
```
# Cleaning
Read and clean the data.
```{r}
data <-
  read_csv(
    raw_data_file, show_col_types = FALSE
  ) %>%
  rename(
    Location = `Reporting County`,
    Year = Date,
    Value = `Opened Investigations & Assessments`
  ) %>%
  mutate(
    Indicator = "abuseneg",
    Location = gsub("All","WA", Location),
  )
```
# Write Clean Data
Write the cleaned data csv file.
```{r}
write_csv(data, cleaned_data_file)
```

